/*
  * This file is auto-generated by apps/app/scripts/assemble-production-build.js!
  * DO NOT EDIT THIS FILE DIRECTLY!
  * This file is used to build the production version of the application.
  * It is not used in development mode.
*/

import { Inject, NgModule } from '@angular/core';
import { ApplicationSlotService, ApplicationSlotServiceToken } from '@extensible-angular-app/sdk';
/*${IMPORTS}*/

@NgModule({
  imports: [
    /*${MODULE_IMPORTS}*/
  ],
})
export class ProductionBuildModule {
  constructor(
    @Inject('config') private config: any,
    @Inject(ApplicationSlotServiceToken) private applicationSlotService: ApplicationSlotService
  ) {
    /*${MODULE_CONSTRUCTOR}*/
  }
}
